import { Colors, Genders, ShoeItem } from "./ShoeItem";

export class ShoeItemData{
    private static shoes:Map<number, ShoeItem> = new Map<number, ShoeItem>;
    private static initID:number = 1;

    private static addItem(name:string, price:number, picture:string, gender:Genders, color:Colors, sizes:string[], description:string, brand:string){
        this.shoes.set(this.initID, new ShoeItem(this.initID, name, price, picture, gender, color, sizes, description, brand));
        this.initID++;
    }

    public static init():void{
        this.addItem("Nike Terminator High OG",199.99, "../assets/shoes/shoe1.png", Genders.M, Colors.Grey, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"],"Untouched, unaltered and straight from the vault—you get the picture. The Terminator High lets you step back to the era of hook shots, knee pads and calf-high socks. Returning to the '85 original (the first signature school shoe by Nike), its throwback colour-blocking lets you rep the '84 champs and the team you love. Crisp leather keeps 'em smoother than backboard glass while retro branding delivers a big varsity finish. It's game time.","Nike");
        this.addItem("Air Max 1 '87",299.99, "../assets/shoes/shoe2.png", Genders.M, Colors.Red ,["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"],"Modernise a classic with this edition of the Air Max 1. The iconic safari print you know from past grails is grounded in calming neutrals, delivering a dose of easy-to-style wild. Embroidered accents on the sides showcase your animal instinct, while premium leather and airy mesh root your look to the original design. Add in some tried-and-tested Nike Air cushioning and that classic wavy mudguard—no wonder it's reigned supreme since 1987.","Nike")
        this.addItem("Air Max Furyosa",79.99, "../assets/shoes/shoe3.png", Genders.F, Colors.Brown, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"Bold '90s-inspired style meets premium construction in your next ride-or-die kicks. Visible Air units draw the eye while delivering world-class cushioning, and ultra-plush padding on the ankle and tongue mean you'll want to wear them all day.","Nike");        
        this.addItem("Air Max 1 '86 Original",89.99, "../assets/shoes/shoe4.png", Genders.M, Colors.MultiColor ,["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"],"With an edgy look inspired by the fast-paced running shoes of the '90s, the Nike Air Max 1 '86 Original brings a powerful new voice to fashion and comfort.Offset, stacked Air in the heel delivers a bold statement in cushioning.Its heel pillow, plush collar and ultra-padded tongue make it feel like you've just stepped into your favourite pair of slippers.If that's not enough, the dual-lace system lets you be as expressive as you want, adding DIY flair to the 5-star comfort.","Nike");
        this.addItem("Nike Cortez",179.99, "../assets/shoes/shoe5.png", Genders.F, Colors.White, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"One word: tradition. From heritage running to fashion phenom, the Cortez's retro appeal, sponge-soft midsole and see-saw detailing deliver decade after decade. This fresh take on the ubiquitous look keeps it classic with a white and black colour combo, while the flash of Light Photo Blue in the midsole adds the perfect amount of energy.","Nike");
        this.addItem("Air Max Scorpion",699.99, "../assets/shoes/shoe6.png", Genders.K, Colors.Black, ["32", "35", "35.5", "36" , "37", "38", "39", "40"],"From the shoe's release year proudly stamped on the \"point-loaded\" Air unit (cushioning that forms to your every step) to the airy chenille upper, its striking visuals deliver a lesson in comfort.","Nike");
        this.addItem("Run Swift 2", 49.99, "../assets/shoes/shoe7.png", Genders.K, Colors.Blue, ["32", "35", "35.5", "36" , "37", "38", "39", "40"],"The Nike Run Swift 2 is designed with shorter miles in mind. An updated yet familiar shape delivers breathable stability. A durable outsole keeps you supported no matter what your pace.","Nike");
        this.addItem("Air Zoom Fire", 179.99, "../assets/shoes/shoe8.png", Genders.F, Colors.White, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"The unconventional look of the Nike Air Zoom Fire nods to the history of performance running sneakers while creating a fresh look through rich textures and multiple layers. Plus, wild design lines, a thick foam midsole and boldly framed Zoom Air cushioning add comfort and balance to your day.","Nike");
        this.addItem("Air Max 95",159.99, "../assets/shoes/shoe9.png", Genders.M, Colors.Red, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"],"The classic is back. Taking inspiration from the human body and '90s athletics style, the Nike Air Max 95 mixes unbelievable comfort with head-turning design. Wavy side panels add natural flow to any outfit while a rich mix of crisp leather, airy knits and mesh gives these kicks a premium look and feel. Plus, Nike Air in the heel and forefoot delivers comfort with every step.","Nike");
        this.addItem("Air Max Excee",239.99, "../assets/shoes/shoe10.png", Genders.M, Colors.Black, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"],"The Nike Air Max Excee honours 30+ years since the release of the iconic Air Max 90. Inspired by the original design, these low-top kicks add a crafty look and a mix of textures for a new twist on a '90s favourite. FYI, Excee means 90 in Latin.","Nike");
        this.addItem("Air Max 97 OG",399.99, "../assets/shoes/shoe11.png", Genders.M, Colors.Yellow, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"],"Push your style full speed ahead with the Nike Air Max 97 OG. Its iconic design takes inspiration from water droplets and Japanese bullet trains. Full-length Nike Air cushioning lets you ride in first-class comfort.","Nike")
        this.addItem("Nike Quest 5",39.99, "../assets/shoes/shoe12.png", Genders.F, Colors.Pink, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"You lace up in pursuit of new personal goals. Let the Nike Quest 5 help you reach those aspirations. This neutral sneaker gives you a smooth, comfortable ride with plenty of traction. We focused on our foam, adding more cushioning for a better transition from heel to toe.","Nike");
        this.addItem("Air Force 1",299.99, "../assets/shoes/shoe13.png", Genders.F, Colors.Orange, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"Score major points in this legendary classic. Crossing hardwood comfort with off-court flair, this hoops original pairs crisp leather with playful pastel Swoosh logos for nothing-but-net style.","Nike");
        this.addItem("Air Jordan 1 Low",179.99, "../assets/shoes/shoe14.png", Genders.F, Colors.Green, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"","Nike");
        this.addItem("Waffle Debut Vintage",399.99, "../assets/shoes/shoe15.png", Genders.K, Colors.Green, ["32", "35", "35.5", "36" , "37", "38", "39", "40"],"With Air cushioning underfoot, a Wings logo on the heel and an integrated traction pattern to help you power through your swing, it delivers all the clubhouse cool of the original AJ1—plus everything you need to play 18 holes in comfort.","Nike");
        this.addItem("Air Max 270",299.99, "../assets/shoes/shoe16.png", Genders.K, Colors.Black, ["32", "35", "35.5", "36" , "37", "38", "39", "40"],"Nike Air isn't just tech—it's a lifestyle. Walk a little lighter in a design drawing inspiration from Air Max icons. The large window showcases Nike's greatest innovation while mesh keeps you feeling fresh.","Nike");
        this.addItem("Air Max Plus",179.99, "../assets/shoes/shoe17.png", Genders.M, Colors.Black, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"],"Let your attitude have the edge with this tuned Nike Air experience that offers premium stability and unbelievable cushioning. Featuring classic '90s style, airy mesh and nature-inspired design lines, it lets you celebrate your defiant style in comfort.","Nike");
        this.addItem("Air Jordan XXXVII",499.99, "../assets/shoes/shoe18.png", Genders.M, Colors.Grey, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"],"You've got the hops and the speed—lace up in shoes that enhance what you bring to the court. The latest AJ is all about takeoffs and landings, with multiple Air units to get you off the ground and our signature Formula 23 foam to cushion your impact. Up top, you'll find layers of tough, reinforced leno-weave fabric that'll keep you contained—and leave your game uncompromised.","Nike");
        this.addItem("Air Force 1 LV8",119.99, "../assets/shoes/shoe19.png", Genders.K, Colors.Yellow, ["32", "35", "35.5", "36" , "37", "38", "39", "40"],"The '90s era? Yeah, that was the bomb. Nike AF-1 style? A favourite forever. We mashed them together to make the Nike Force 1 LV8.","Nike");
        this.addItem("Air Max Bliss", 189.99, "../assets/shoes/shoe20.png", Genders.F, Colors.Yellow, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"You know the saying: Beauty is pain. Not so with the Air Max Bliss. Bridging elegant design lines with modern technology, it delivers head-turning style and unbelievable comfort. The rich mixture of textures and Air cushioning keep it fun to style and blissful to wear.","Nike");
        this.addItem("Metcon 8",399.99, "../assets/shoes/shoe21.png", Genders.F, Colors.MultiColor, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"You chase the clock, challenging and encouraging each other all in the name of achieving goals and making gains. Our go-to model for training relies on a lighter, more breathable upper than our previous edition to complement our standards of durability and comfort, so that you can float through your cardio, power through your lifts and dominate your workouts.","Nike");
        this.addItem("Nike Court Legacy", 39.99, "../assets/shoes/shoe22.png", Genders.K, Colors.White, ["32", "35", "35.5", "36" , "37", "38", "39", "40"],"Elevate your style with the Nike Court Legacy. Its platform midsole delivers a bold statement on top of the classic, easy-to-wear design. And don't worry, we've kept the fit you love.","Nike");
        this.addItem("Air Max 170", 189.99, "../assets/shoes/shoe23.png", Genders.M, Colors.White, ["32", "35", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48"],"Let your attitude have the edge in your Nike Air Max Plus, a Tuned Air experience that offers premium stability and unbelievable cushioning. Featuring the original's wavy design lines, TPU accents and airy mesh on the upper, it celebrates defiant style.","Nike");
        this.addItem("Air Force 1 Premium", 399.99, "../assets/shoes/shoe24.png", Genders.F, Colors.Grey, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"They say the way to the heart is through chocolate. They're wrong. Lace into true bliss with this crafted take on the b-ball original. Pairing smooth leather with waxed laces, it delivers love at first sight. The leather tongue label and dubrae add an artisan touch while Air cushioning puts the cherry on the bottom—setting you softly on cloud 9.","Nike");
        this.addItem("Jordan Post", 29.99, "../assets/shoes/shoe25.png", Genders.M, Colors.Red, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"],"Quick, comfy, cool. These slides are made from robust, flexible foam that will stay secure as you rack up those steps. Wide foot coverage holds your feet in place while the asymmetrical design gives you a distinct look.","Nike");
        this.addItem("Super Rep Go 3", 159.99, "../assets/shoes/shoe26.png", Genders.F, Colors.Red, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"A finely ground, reclaimed foam midsole gives you responsive cushioning for high-impact training. The lightweight, packable design lets you keep them close, no matter where your next workout takes you.","Nike");
        this.addItem("Air Max Plus 3", 229.99, "../assets/shoes/shoe27.png", Genders.F, Colors.MultiColor, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"],"Taking the best from past generations, this Air Max Plus 3 honours Air heritage with subtle nods to its predecessors. Futuristic design lines, soft foam and Max Air units bring these kicks into the present day with eye-catching style and comfort. Plus, vibrant layered Swoosh logos inspired by the 40th anniversary of the Pegasus help you rep running legacy with every step.","Nike");
        this.addItem("Samba Classic", 74.99, "../assets/shoes/shoe28.png", Genders.M, Colors.Black, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"], "Getting up and down the field with speed is the name of the indoor game. The Samba has dominated indoor soccer for decades for a reason. These legendary shoes feature a leather upper and a lightweight EVA midsole for better response on indoor surfaces.","Adidas")
        this.addItem("Gazelle", 129.99, "../assets/shoes/shoe29.png", Genders.K, Colors.Blue, ["32", "35", "35.5", "36" , "37", "38", "39", "40"], "From soccer fans in the '60s and '70s to skaters and indie rockers in the '90s, the adidas Gazelle shoes have traversed the entirety of our cultural landscape. These juniors' sneakers are a one-to-one reissue of the 1991 Gazelle, with the same materials, proportions and textures as the original. Serrated 3-Stripes and a classic silhouette add timeless style to every look.", "Adidas");
        this.addItem("Cloudfoam Pure 2.0", 89.99, "../assets/shoes/shoe30.png", Genders.F, Colors.Grey, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"], "Step into these shoes for crisp, clean style and comfort. Thanks to their heritage adidas vibes, these running-inspired trainers make it easy to look calm, cool and collected. Whether you're hanging out with friends or trying not to get frazzled as you tick off your weekend to-do list, stay comfortable through it all. This product is made with Primegreen, a series of high-performance recycled materials.", "Adidas");
        this.addItem("Ultraboost 5.0 DNA", 379.99, "../assets/shoes/shoe31.png", Genders.F, Colors.Black, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"], "These sneakers are the ultimate multitasker. Rooted in running but flush with street-ready style, they're built for whatever your day brings. adidas PRIMEKNIT wraps the foot for a supportive fit that enhances every move. The BOOST midsole provides instant comfort and energy return with each step to keep you going strong.", "Adidas");
        this.addItem("Rider FV Pop FS", 199.99, "../assets/shoes/shoe32.png", Genders.M, Colors.Grey, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"], "The newest addition to the Rider family is celebrating the past while standing firmly in the present – just like the people who wear it. Rider FV is all about a combination of past and future, with a nostalgic, heritage-inspired upper and fresh tooling. This execution features a nylon upper with suede overlays.", "Puma")
        this.addItem("MIRACULOUS RS-X", 149.99, "../assets/shoes/shoe33.png", Genders.K, Colors.Red, ["32", "35", "35.5", "36" , "37", "38", "39", "40"], "We teamed up with after-school favourite TV series Miraculous: Tales of Ladybug & Cat Noir to create the all-new PUMA x MIRACULOUS collection. This version of the RS-X sneaker is directly inspired by the show's main character, Ladybug, with a statement polka dot pattern all over the upper.", "Puma");
        this.addItem("Ultraboost Light", 379.99, "../assets/shoes/shoe34.png", Genders.M, Colors.Red, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"], "Go bold and bright with the Ultraboost Light red colorway, exclusive to adidas stores. Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever. The magic lies in the Light BOOST midsole, a new generation of adidas BOOST. Its unique molecule design achieves the lightest BOOST foam to date and boasts a 10% lower carbon footprint than previous models. With ultimate cushioning, comfort and responsiveness, some feet really can have it all.", "Adidas");
        this.addItem("Trae Young 2.0", 179.99,  "../assets/shoes/shoe35.png", Genders.F, Colors.Yellow, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"], "One of the coldest on the hardwood, Trae Young is absolutely fearless. He'll take any shot at any time, and when it's all on the line, look out, because Trae is about to steal the show. The newest signature shoes from adidas Basketball and Trae Young are all about agility and speed, the two elements that make Trae so dynamic. BOOST and Lightstrike work in tandem with an adaptive SCK360, semi-laceless upper to deliver enhanced comfort and game-changing support.", "Adidas")
        this.addItem("Dame 8 Basketball", 99.99, "../assets/shoes/shoe36.png", Genders.K, Colors.Blue, ["32", "35", "35.5", "36" , "37", "38", "39", "40"], "Respect is earned. Damian Lillard made his name by showing up in the moments that matter the most, when everything is on the line. These junior's signature shoes from adidas Basketball and Dame celebrate one of the game's best closers with Dame graphics and a colorful upper inspired by the first time he competed with and beat some of the best hoopers in the world. The outsole and Bounce Pro midsole are designed specifically for Dame's lethal combination of speed and precision.Made in part with recycled content generated from production waste, e.g., cutting scraps, and post-consumer household waste to avoid the larger environmental impact of producing virgin content.","Adidas");
        this.addItem("Shuffle Trainers", 149.99, "../assets/shoes/shoe37.png", Genders.F, Colors.Black, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"], "Change up your wardrobe with a fresh infusion of style in our PUMA Shuffle Trainers. This sweet shoe features sleek classic detailing and comfort technology.", "Puma");
        this.addItem("Rise NITRO", 319.99, "../assets/shoes/shoe38.png", Genders.F, Colors.MultiColor, ["35", "36", "36.5", "38", "38.5", "39", "40", "40.5", "41", "42", "43", "44", "44.5"], "With a breathable engineered mesh upper, a NITRO Infused midsole to get you way above the hoop, and a stabilising PROPLATE to handle all your defence-beating Euro steps, you’ll be playing your best game every time you step onto the court.", "Puma");
        this.addItem("FUTURE Match MG", 129.99, "../assets/shoes/shoe39.png", Genders.M, Colors.MultiColor, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"], "The FUTURE is back, and so are the back-heels, stepovers, and no-look passes. The re-engineered mid-cut construction combines fit and agility so you can create without constraints through to the final whistle. On this Match version, a FUZIONFIT360 upper provides an even more adaptive, even more supportive fit. Stable at the heel and flexible at the forefoot, the second-generation Dynamic Motion System outsole provides traction and agility for unpredictable changes of direction. Free to move. Free to play. Free to create.", "Puma");
        this.addItem("Slipstream Suede FS", 64.99, "../assets/shoes/shoe40.png", Genders.K, Colors.White, ["27.5", "28", "28.5", "29", "30", "31", "32", "33", "34", "34.5"], "A high-flying, slam-dunking, statement-making basketball sneaker. Now, it’s joined by the Slipstream – a rework of the original that brings an all-new energy to the game while staying true to the OG’s sporting roots.", "Puma");
        this.addItem("Renegade MC", 299.99, "../assets/shoes/shoe41.png", Genders.M, Colors.Grey, ["36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5", "48", "49"], "Renegade MC has a rebellious look, thanks to the statement sole and metallic silver palette, that brings the disruptive energy of the race team to the street.", "Puma");
        this.addItem("RBD Game Low", 89.99, "../assets/shoes/shoe42.png", Genders.F, Colors.White, ["35", "36", "38", "40" , "42", "43", "44", "45", "45.5", "46", "47", "47.5"], "The casual throwback style captures the essence of old-school cool, featuring the classic PUMA Formstrip in a contrast design and subtle big-cat branding. Step it back to the classics in these stunning sneakers.", "Puma");

        console.log("Initialising:",this.shoes);
    }

    public static has(id: number):boolean{
        return this.shoes.has(id);
    }

    public static getById(id:number):ShoeItem{
        return this.shoes.get(id)!;
    }

    public static getAll():ReadonlyMap<number, ShoeItem>{
        return this.shoes;
    }

    public static getByGender(gender: Genders):ReadonlyMap<number, ShoeItem>{
        let result: Map<number, ShoeItem> = new Map<number, ShoeItem>();
        this.shoes.forEach((v,k) => {
            if(v.Gender === gender){
                result.set(k, v);
            }
        });
        return result;
    }

}